### PR TITLE
Python3 compatibility and Pep8 fixes

### PR DESCRIPTION
**Pull request by pbdeuchler**
What the title says

### CODE REVIEW

**Comment by keyphact** [comment]
@tejado care to have a look, don't really want to merge this in just yet.

**Comment by PokeAlert** [comment]
I tried it works

**Comment by wchill** [comment]
This looks good to me at first glance.

**Comment by DangerousHIV** [comment]
so theres a way to get this bot working again....sorry to comment here will there every be a download limk so you dont have to go through all this to get it working

**Comment by skerdi22** [comment]
how to make it work with this keyphact?

**Pull request merged**
