### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by Noctem**
Resolved the new conflicts.

### CODE REVIEW

**Comment by globeriz** [comment]
changes consistent with #64, merging.

**Comment by Noctem** [comment]
@globeriz Thanks, and yeah: I just force pushed the fixes to the same branch.

**Comment by oceanor** [comment]
thanks, great one :)
how does this works exactly? I've tried using api.set_proxy("socks5://address:port")
but still works on local with ip not banned and doesn't work on a banned ip. Seems that it's still using the non-proxy ip ^^

**Comment by Vitaefinis** [comment]
I can confirm the issue above

**Comment by ottowayne** [comment]
I haven't tried it yet but did you update your pip requirements?

**Comment by ph3l1x** [comment]
How do I use this? Can I just bind to a specific IP on my machine? Is it something that needs added into the config file ?? Any chance of a quick write up on how to use this?

**Comment by Noctem** [comment]
`set_proxy` expects a dict with `http` and `https` keys, like so:
```python
PROXIES = {
    'http': 'socks5://127.0.0.1:1080',
    'https': 'socks5://127.0.0.1:1080'
}

api = PGoApi()
api.set_proxy(PROXIES)
```
[More information available here.](http://docs.python-requests.org/en/master/user/advanced/#proxies)

**Pull request merged**
