### PR TITLE
Added scripts\accept-tos.py

### PR DESCRIPTION
**Pull request by scottstamp**
Added an example script for accepting terms of service.

### CODE REVIEW

**Comment by nevrending** [comment]
@scottstamp Thanks for sharing this, it works!

**Comment by keyphact** [comment]
+1

**Comment by dnsBlah** [comment]
I'm getting responses like:
`got multiple values for keyword argument 'completed_tutorials'`

**Comment by scottstamp** [comment]
Can anyone confirm? @dnsBlah

**Comment by globeriz** [comment]
works fine for me, just checked

**Comment by dnsBlah** [comment]
@globeriz could you show me some input you use ?

**Pull request merged**
