### PR TITLE
Fix proxies with reused sessions

### PR DESCRIPTION
**Pull request by Noctem**
The proxy code got left behind when sessions were moved to the PGoApi object, so I applied it to the new sessions and simplified the code.

### CODE REVIEW

**Comment by ottowayne** [comment]
Can confirm that this fixed my error:
`RpcApi instance has no attribute '_session'`

**Comment by jmangeja1** [comment]
So i can complete other api calls such as release pokemon, get_player.. but get_mpa_objects returns empty cells when I use a free socks5 proxy? Any idea why?

**Comment by Noctem** [comment]
@jmangeja1 Does it work when you're not using a proxy? And did you `api.activate_signature(lib_path)`?

**Comment by jmangeja1** [comment]
@noctem It works when not using a proxy. And I have that line in the library code

**Comment by Noctem** [comment]
@jmangeja1 I'm guessing the IP of the proxy is soft-banned (likely temporarily, dependent on traffic).

**Pull request merged**
