### PR TITLE
PEP8 Cleanup

### PR DESCRIPTION
**Pull request by echos-code**
This is a carry over from #68 since it is locked out due to rebasing.

* Cleaned up code according to the Python style guide ([PEP-8](https://www.python.org/dev/peps/pep-0008/))
* Removed unused imports
* Removed `future` dependency, replacing it with the existing `six` dependency
* Fixes mixing of tabs and spaces in python files as well 2 space indents
* Adds `.editorconfig` to reduce the former from happening

### CODE REVIEW

**Comment by keyphact** [comment]
Branch has conflicts I'm afraid, can you fix this and re-submit?

**Comment by echos-code** [comment]
Hmm, github is not updating the pull request. I have a version that will merge into master cleanly.

**Comment by echos-code** [comment]
Just did a rebase, should be all good

**Comment by wchill** [comment]
Gonna need another rebase @echos-code

**Pull request closed without merging**
